export const ADMIN_LOGIN_START = 'ADMIN_LOGIN_START'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR'

export const ADMIN_CHANGE_PASSWORD_START = 'ADMIN_CHANGE_PASSWORD_START'
export const ADMIN_CHANGE_PASSWORD_SUCCESS = 'ADMIN_CHANGE_PASSWORD_SUCCESS'
export const ADMIN_CHANGE_PASSWORD_ERROR = 'ADMIN_CHANGE_PASSWORD_ERROR'

export const ADMIN_FORGOT_PASSWORD_START = 'ADMIN_FORGOT_PASSWORD_START'
export const ADMIN_FORGOT_PASSWORD_SUCCESS = 'ADMIN_FORGOT_PASSWORD_SUCCESS'
export const ADMIN_FORGOT_PASSWORD_ERROR = 'ADMIN_FORGOT_PASSWORD_ERROR'

export const ADMIN_RESET_PASSWORD_START = 'ADMIN_RESET_PASSWORD_START'
export const ADMIN_RESET_PASSWORD_SUCCESS = 'ADMIN_RESET_PASSWORD_SUCCESS'
export const ADMIN_RESET_PASSWORD_ERROR = 'ADMIN_RESET_PASSWORD_ERROR'

export const ADMIN_LOGOUT_START = 'ADMIN_LOGOUT_START'
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS'
export const ADMIN_LOGOUT_ERROR = 'ADMIN_LOGOUT_ERROR'

export const LOAD_ADMIN_START = 'LOAD_ADMIN_START'
export const LOAD_ADMIN_SUCCESS = 'LOAD_ADMIN_SUCCESS'
export const LOAD_ADMIN_ERROR = 'LOAD_ADMIN_ERROR'

export const CREATE_ADMIN_START = 'CREATE_ADMIN_START'
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS'
export const CREATE_ADMIN_ERROR = 'CREATE_ADMIN_ERROR'

export const GET_SINGLE_ADMIN_START = 'GET_SINGLE_ADMIN_START'
export const GET_SINGLE_ADMIN_SUCCESS = 'GET_SINGLE_ADMIN_SUCCESS'
export const GET_SINGLE_ADMIN_ERROR = 'GET_SINGLE_ADMIN_ERROR'

export const UPDATE_ADMIN_START = 'UPDATE_ADMIN_START'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_ERROR = 'UPDATE_ADMIN_ERROR'

// export const DELETE_ADMIN_START = 'DELETE_ADMIN_START'
// export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS'
// export const DELETE_ADMIN_ERROR = 'DELETE_ADMIN_ERROR'
