export const LOAD_BANNER_IMAGE_START = 'LOAD_BANNER_IMAGE_START'
export const LOAD_BANNER_IMAGE_SUCCESS = 'LOAD_BANNER_IMAGE_SUCCESS'
export const LOAD_BANNER_IMAGE_ERROR = 'LOAD_BANNER_IMAGE_ERROR'

export const GET_SINGLE_BANNER_IMAGE_START = 'GET_SINGLE_BANNER_IMAGE_START'
export const GET_SINGLE_BANNER_IMAGE_SUCCESS = 'GET_SINGLE_BANNER_IMAGE_SUCCESS'
export const GET_SINGLE_BANNER_IMAGE_ERROR = 'GET_SINGLE_BANNER_IMAGE_ERROR'

export const CREATE_BANNER_IMAGE_START = 'CREATE_BANNER_IMAGE_START'
export const CREATE_BANNER_IMAGE_SUCCESS = 'CREATE_BANNER_IMAGE_SUCCESS'
export const CREATE_BANNER_IMAGE_ERROR = 'CREATE_BANNER_IMAGE_ERROR'

export const DELETE_BANNER_IMAGE_START = 'DELETE_BANNER_IMAGE_START'
export const DELETE_BANNER_IMAGE_SUCCESS = 'DELETE_BANNER_IMAGE_SUCCESS'
export const DELETE_BANNER_IMAGE_ERROR = 'DELETE_BANNER_IMAGE_ERROR'

export const UPDATE_BANNER_IMAGE_START = 'UPDATE_BANNER_IMAGE_START'
export const UPDATE_BANNER_IMAGE_SUCCESS = 'UPDATE_BANNER_IMAGE_SUCCESS'
export const UPDATE_BANNER_IMAGE_ERROR = 'UPDATE_BANNER_IMAGE_ERROR'