export const LOAD_CAMPANING_START = 'LOAD_CAMPANING_START'
export const LOAD_CAMPANING_SUCCESS = 'LOAD_CAMPANING_SUCCESS'
export const LOAD_CAMPANING_ERROR = 'LOAD_CAMPANING_ERROR'

export const GET_SINGLE_CAMPANING_START = 'GET_SINGLE_CAMPANING_START'
export const GET_SINGLE_CAMPANING_SUCCESS = 'GET_SINGLE_CAMPANING_SUCCESS'
export const GET_SINGLE_CAMPANING_ERROR = 'GET_SINGLE_CAMPANING_ERROR'

export const CREATE_CAMPANING_START = 'CREATE_CAMPANING_START'
export const CREATE_CAMPANING_SUCCESS = 'CREATE_CAMPANING_SUCCESS'
export const CREATE_CAMPANING_ERROR = 'CREATE_CAMPANING_ERROR'

export const DELETE_CAMPANING_START = 'DELETE_CAMPANING_START'
export const DELETE_CAMPANING_SUCCESS = 'DELETE_CAMPANING_SUCCESS'
export const DELETE_CAMPANING_ERROR = 'DELETE_CAMPANING_ERROR'

export const UPDATE_CAMPANING_START = 'UPDATE_CAMPANING_START'
export const UPDATE_CAMPANING_SUCCESS = 'UPDATE_CAMPANING_SUCCESS'
export const UPDATE_CAMPANING_ERROR = 'UPDATE_CAMPANING_ERROR'