export const LOAD_CHILD_SUBCATEGORY_START = 'LOAD_CHILD_SUBCATEGORY_START'
export const LOAD_CHILD_SUBCATEGORY_SUCCESS = 'LOAD_CHILD_SUBCATEGORY_SUCCESS'
export const LOAD_CHILD_SUBCATEGORY_ERROR = 'LOAD_CHILD_SUBCATEGORY_ERROR'

export const GET_SINGLE_CHILD_SUBCATEGORY_START = 'GET_SINGLE_CHILD_SUBCATEGORY_START'
export const GET_SINGLE_CHILD_SUBCATEGORY_SUCCESS = 'GET_SINGLE_CHILD_SUBCATEGORY_SUCCESS'
export const GET_SINGLE_CHILD_SUBCATEGORY_ERROR = 'GET_SINGLE_CHILD_SUBCATEGORY_ERROR'

export const CREATE_CHILD_SUBCATEGORY_START = 'CREATE_CHILD_SUBCATEGORY_START'
export const CREATE_CHILD_SUBCATEGORY_SUCCESS = 'CREATE_CHILD_SUBCATEGORY_SUCCESS'
export const CREATE_CHILD_SUBCATEGORY_ERROR = 'CREATE_CHILD_SUBCATEGORY_ERROR'

export const DELETE_CHILD_SUBCATEGORY_START = 'DELETE_CHILD_SUBCATEGORY_START'
export const DELETE_CHILD_SUBCATEGORY_SUCCESS = 'DELETE_CHILD_SUBCATEGORY_SUCCESS'
export const DELETE_CHILD_SUBCATEGORY_ERROR = 'DELETE_CHILD_SUBCATEGORY_ERROR'

export const UPDATE_CHILD_SUBCATEGORY_START = 'UPDATE_CHILD_SUBCATEGORY_START'
export const UPDATE_CHILD_SUBCATEGORY_SUCCESS = 'UPDATE_CHILD_SUBCATEGORY_SUCCESS'
export const UPDATE_CHILD_SUBCATEGORY_ERROR = 'UPDATE_CHILD_SUBCATEGORY_ERROR'