export const LOAD_LATEST_NEWS_START = 'LOAD_LATEST_NEWS_START'
export const LOAD_LATEST_NEWS_SUCCESS = 'LOAD_LATEST_NEWS_SUCCESS'
export const LOAD_LATEST_NEWS_ERROR = 'LOAD_LATEST_NEWS_ERROR'

export const GET_SINGLE_LATEST_NEWS_START = 'GET_SINGLE_LATEST_NEWS_START'
export const GET_SINGLE_LATEST_NEWS_SUCCESS = 'GET_SINGLE_LATEST_NEWS_SUCCESS'
export const GET_SINGLE_LATEST_NEWS_ERROR = 'GET_SINGLE_LATEST_NEWS_ERROR'

export const CREATE_LATEST_NEWS_START = 'CREATE_LATEST_NEWS_START'
export const CREATE_LATEST_NEWS_SUCCESS = 'CREATE_LATEST_NEWS_SUCCESS'
export const CREATE_LATEST_NEWS_ERROR = 'CREATE_LATEST_NEWS_ERROR'

export const DELETE_LATEST_NEWS_START = 'DELETE_LATEST_NEWS_START'
export const DELETE_LATEST_NEWS_SUCCESS = 'DELETE_LATEST_NEWS_SUCCESS'
export const DELETE_LATEST_NEWS_ERROR = 'DELETE_LATEST_NEWS_ERROR'

export const UPDATE_LATEST_NEWS_START = 'UPDATE_LATEST_NEWS_START'
export const UPDATE_LATEST_NEWS_SUCCESS = 'UPDATE_LATEST_NEWS_SUCCESS'
export const UPDATE_LATEST_NEWS_ERROR = 'UPDATE_LATEST_NEWS_ERROR'