export const LOAD_METTERS_START = 'LOAD_METTERS_START'
export const LOAD_METTERS_SUCCESS = 'LOAD_METTERS_SUCCESS'
export const LOAD_METTERS_ERROR = 'LOAD_METTERS_ERROR'

export const GET_SINGLE_METTERS_START = 'GET_SINGLE_METTERS_START'
export const GET_SINGLE_METTERS_SUCCESS = 'GET_SINGLE_METTERS_SUCCESS'
export const GET_SINGLE_METTERS_ERROR = 'GET_SINGLE_METTERS_ERROR'

export const CREATE_METTERS_START = 'CREATE_METTERS_START'
export const CREATE_METTERS_SUCCESS = 'CREATE_METTERS_SUCCESS'
export const CREATE_METTERS_ERROR = 'CREATE_METTERS_ERROR'

export const DELETE_METTERS_START = 'DELETE_METTERS_START'
export const DELETE_METTERS_SUCCESS = 'DELETE_METTERS_SUCCESS'
export const DELETE_METTERS_ERROR = 'DELETE_METTERS_ERROR'

export const UPDATE_METTERS_START = 'UPDATE_METTERS_START'
export const UPDATE_METTERS_SUCCESS = 'UPDATE_METTERS_SUCCESS'
export const UPDATE_METTERS_ERROR = 'LOAD_METTERS_ERROR'