export const LOAD_SUBCATEGORY_START = 'LOAD_SUBCATEGORY_START'
export const LOAD_SUBCATEGORY_SUCCESS = 'LOAD_SUBCATEGORY_SUCCESS'
export const LOAD_SUBCATEGORY_ERROR = 'LOAD_SUBCATEGORY_ERROR'

export const GET_SINGLE_SUBCATEGORY_START = 'GET_SINGLE_SUBCATEGORY_START'
export const GET_SINGLE_SUBCATEGORY_SUCCESS = 'GET_SINGLE_SUBCATEGORY_SUCCESS'
export const GET_SINGLE_SUBCATEGORY_ERROR = 'GET_SINGLE_SUBCATEGORY_ERROR'

export const CREATE_SUBCATEGORY_START = 'CREATE_SUBCATEGORY_START'
export const CREATE_SUBCATEGORY_SUCCESS = 'CREATE_SUBCATEGORY_SUCCESS'
export const CREATE_SUBCATEGORY_ERROR = 'CREATE_SUBCATEGORY_ERROR'

export const DELETE_SUBCATEGORY_START = 'DELETE_SUBCATEGORY_START'
export const DELETE_SUBCATEGORY_SUCCESS = 'DELETE_SUBCATEGORY_SUCCESS'
export const DELETE_SUBCATEGORY_ERROR = 'DELETE_SUBCATEGORY_ERROR'

export const UPDATE_SUBCATEGORY_START = 'UPDATE_SUBCATEGORY_START'
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS'
export const UPDATE_SUBCATEGORY_ERROR = 'LOAD_SUBCATEGORY_ERROR'
