export const LOAD_USER_START = 'LOAD_USER_START'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR'

export const LOAD_USER_CONTACTLIST_START = 'LOAD_USER_CONTACTLIST_START'
export const LOAD_USER_CONTACTLIST_SUCCESS = 'LOAD_USER_CONTACTLIST_SUCCESS'
export const LOAD_USER_CONTACTLIST_ERROR = 'LOAD_USER_CONTACTLIST_ERROR'